pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

rootProject.name = 'MolecularARViewer'

include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')

def nodeModules = new File(rootProject.projectDir, '../node_modules')
def cliPath = new File(nodeModules, '@react-native-community/cli-platform-android')
if (cliPath.exists()) {
    apply from: new File(cliPath, 'native_modules.gradle')
    applyNativeModulesSettingsGradle(this)
}
